#!/bin/bash
 STRATUM_DIR=/var/stratum
 
 screen -dmS groestl $STRATUM_DIR/run.sh groestl
 screen -dmS keccak $STRATUM_DIR/run.sh keccak
 screen -dmS neoscrypt $STRATUM_DIR/run.sh neo
 screen -dmS nist5 $STRATUM_DIR/run.sh nist5
 screen -dmS quark $STRATUM_DIR/run.sh quark
 screen -dmS scrypt $STRATUM_DIR/run.sh scrypt
 screen -dmS skein $STRATUM_DIR/run.sh skein
 screen -dmS x11 $STRATUM_DIR/run.sh x11
 screen -dmS x16rv2 $STRATUM_DIR/run.sh x16rv2
 screen -dmS c11 $STRATUM_DIR/run.sh c11
 screen -dmS deep $STRATUM_DIR/run.sh deep
 screen -dmS x11evo $STRATUM_DIR/run.sh x11evo
 screen -dmS x13 $STRATUM_DIR/run.sh x13
 screen -dmS x14 $STRATUM_DIR/run.sh x14
 screen -dmS x15 $STRATUM_DIR/run.sh x15
 screen -dmS x16r $STRATUM_DIR/run.sh x16r
 screen -dmS x17 $STRATUM_DIR/run.sh x17
 screen -dmS xevan $STRATUM_DIR/run.sh xevan
 screen -dmS timetravel $STRATUM_DIR/run.sh timetravel
 screen -dmS bitcore $STRATUM_DIR/run.sh bitcore
 screen -dmS hmq1725 $STRATUM_DIR/run.sh hmq1725
 screen -dmS tribus $STRATUM_DIR/run.sh tribus
 screen -dmS sha $STRATUM_DIR/run.sh sha
 screen -dmS sha256t $STRATUM_DIR/run.sh sha256t
 screen -dmS scryptn $STRATUM_DIR/run.sh scryptn
 screen -dmS luffa $STRATUM_DIR/run.sh luffa
 screen -dmS penta $STRATUM_DIR/run.sh penta
 screen -dmS qubit $STRATUM_DIR/run.sh qubit
 screen -dmS jha $STRATUM_DIR/run.sh jha
 screen -dmS dmd-gr $STRATUM_DIR/run.sh dmd-gr
 screen -dmS myr-gr $STRATUM_DIR/run.sh myr-gr
 screen -dmS lbry $STRATUM_DIR/run.sh lbry
 screen -dmS allium $STRATUM_DIR/run.sh allium
 screen -dmS lyra2 $STRATUM_DIR/run.sh lyra2
 screen -dmS lyra2v2 $STRATUM_DIR/run.sh lyra2v2
 screen -dmS zero $STRATUM_DIR/run.sh lyra2z
 screen -dmS blakecoin $STRATUM_DIR/run.sh blakecoin
 screen -dmS blake $STRATUM_DIR/run.sh blake
 screen -dmS blake2s $STRATUM_DIR/run.sh blake2s
 screen -dmS vanilla $STRATUM_DIR/run.sh vanilla
 screen -dmS decred $STRATUM_DIR/run.sh decred
 screen -dmS keccakc $STRATUM_DIR/run.sh keccakc
 screen -dmS phi $STRATUM_DIR/run.sh phi
 screen -dmS polytimos $STRATUM_DIR/run.sh polytimos
 screen -dmS whirlpool $STRATUM_DIR/run.sh whirlpool
 screen -dmS skein2 $STRATUM_DIR/run.sh skein2
 screen -dmS yescrypt $STRATUM_DIR/run.sh yescrypt
 screen -dmS yescryptR16 $STRATUM_DIR/run.sh yescryptR16
 screen -dmS zr5 $STRATUM_DIR/run.sh zr5
 screen -dmS sib $STRATUM_DIR/run.sh sib
 screen -dmS m7m $STRATUM_DIR/run.sh m7m
 screen -dmS veltor $STRATUM_DIR/run.sh veltor
 screen -dmS velvet $STRATUM_DIR/run.sh velvet
 screen -dmS argon2 $STRATUM_DIR/run.sh argon2